### PR TITLE
fixed ign_uppercase_variables option handling

### PR DESCRIPTION
**Pull request by kkreplin**

### CODE REVIEW

**Comment by sejans** [comment]
Hey! Thanks for commit, but before pull I wanted to repeat the problem, and couldnt. For me it works with  `pyminifier  --obfuscate-variables --ignore-uppercase-variables --prepend=copyright.txt -d result test.py`
tried also different launch params
`pyminifier --obfuscate-variables -o obf/test.py orig/test.py --prepend=copyright.txt`
but it also works, please could you write how you got that error what command you used?

**Comment by sejans** [comment]
options variable in obfuscate should already get the params... khm.

**Comment by sejans** [comment]
My guess is that you somehow managed to call obfuscate without all params, or **please check your **main**.py file at line 123**, there shuold be code like this - which should guarantee that there is variable **ign_uppercase_variables**

```
parser.add_option(
        "--ignore-uppercase-variables",
        action="store_true",
        dest="ign_uppercase_variables",
        default=False,
        help="Ignore uppercase variable names."
    )
```

Waiting for your answer

**Comment by kkreplin** [comment]
Ok, so what I did was:
- install pyminifier via pip under python3.4 getting version 2.1
- clone your github master and do a cp -r pyminifier/pyminifier into my site-packages

running it, I get the error:

```
Traceback (most recent call last):
  File "/home/katharina/anaconda2/envs/python3p4/bin/pyminifier", line 11, in <module>
    sys.exit(main())
  File "/home/katharina/anaconda2/envs/python3p4/lib/python3.4/site-packages/pyminifier/pyminifier.py", line 408, in main
    obfuscate.obfuscate(module, tokens, options)
  File "/home/katharina/anaconda2/envs/python3p4/lib/python3.4/site-packages/pyminifier/obfuscate.py", line 771, in obfuscate
    tokens, obfuscatable_variable, ign_uppercase_variables=options.ign_uppercase_variables)
AttributeError: 'Values' object has no attribute 'ign_uppercase_variables'
```

Then I did the fix described above and I got it running.

In **main**.py I have the ign_uppercase_variables code as described above.

**Comment by sejans** [comment]
Thanks for clarification!
So yes, this way it won't work I repeated the problem.
I mean this is not correctly replacing the installed package (clone your github master and do a cp -r pyminifier/pyminifier into my site-packages)

You can even try to write **pyminifier --v** and you will get **2.1 version, however it should be 2.2**, if you use clone correctly.
Another sign is that if you type **pyminifier --h** you wont see there the repo added feature - e.g.
`--ignore-uppercase-variables
                        Ignore uppercase variable names.`
However with repo you should.

So I figured out the fastest way to fix this for you:
1) Go to site-packages/pyminifier and there should be two files **`__main__.py` (this is from repo 2.2) and pyminifier.py (this is from pip 2.1)**
2) Delete **pyminifier.py and rename `__main__.py` to pyminifier.py**
3) Now check out command **pyminifier --v** it should be 2.2, and check **pyminifier --h** it should give you more options, like mentioned **--ignore-uppercase-variables**

p.s. in repo the pyminifier.py is infact `__main__.py` thus the copying files doesnt replace pyminifier.py, but adds it. And because the old one is left, the functionality is old.

Let me know if it worked for you and Ill close this pull request, because it is not needed.

**Comment by kkreplin** [comment]
Hi Janis,

thanks for your answer. I followed the steps you recommended.
Indeed, the pyminifier version is now correctly set to 2.2!
However, the obfuscated output doesn't come out any more. I'm getting this now:

```
pyminifier --obfuscate-variables test.py 
test.py (2002) reduced to 943 bytes (47.1% of original size)
Overall size reduction: 47.1% of original size
```

Where does the obfuscated output go now?

Best regards,
Katharina

**Comment by sejans** [comment]
Very nice Katharina!
So about output:
In this case, because you didnt provide where the output must go - it automatically creates folder **minified** and puts the output file there.
`pyminifier --obfuscate-variables test.py`

If you want to convert to specific output folder, use -d param, like the following will put all **into result folder**
`pyminifier --obfuscate-variables -d result test.py`

p.s. can i close this pull request?
p.s.2. my guess is that there is a issue to be solved with output file -o option ill check out

**Comment by sejans** [comment]
Created issue https://github.com/sejans/pyminifier/issues/11

**Comment by kkreplin** [comment]
All right, yeah, thanks. I wasn't aware of the change of this functionality. Before the minified output was written to stdout.
For me, the previous stdout functionality was better because I could keep my folder and subfolder structures of my python module.

Yes, please close this pull request.
Thanks.

**Comment by sejans** [comment]
I understand - ill fix #11 so subscribe to it and you will know when stdout is back

**Pull request closed without merging**
